name: CI Pipeline for Project

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Jayvee
        run: |
          npm install -g @jvalue/jayvee-interpreter

      - name: Run Tests
        run: |
          chmod +x project/test.sh
          ./project/test.sh
