name: CI Pipeline for Jayvee

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python and Jayvee
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Install Dependencies
        run: |
          pip install jayvee
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          chmod +x tests.sh
          ./tests.sh
