name: Run Project Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found. Skipping dependencies installation."
          fi

      - name: Run Project Tests
        run: |
          if [ -f ./project/tests.sh ]; then
            chmod +x ./project/tests.sh
            ./project/tests.sh
          else
            echo "No tests.sh script found in ./project. Skipping tests execution."
          fi

      - name: Cleanup
        run: |
          echo "Cleanup done. All tests finished successfully."
